use_api: false
model_a:
  model_name: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
  max_new_tokens: 64
  temperature: 0.7
model_b:
  model_name: "Qwen/Qwen2.5-0.5B-Instruct"
  max_new_tokens: 64
  temperature: 0.7
