# ================================
# Fichier de configuration global du runner
# ================================

defaults:
  # Mode d’exécution :
  # - "api"   → API Hugging Face
  # - "local" → (réservé si tu ajoutes un client local)
  mode: "api"

  # Type d’appariement :
  # - "pairs"  → toutes les combinaisons A!=B
  # - "self"   → A→A
  # - "random" → paires aléatoires
  pairing: "pairs"

  # Sélection des prompts :
  # - "auto"          → toute la banque de prompts
  # - "manual-bank"   → choix d’IDs dans la banque
  # - "manual-input"  → saisie au clavier
  prompt_mode: "auto"

  # Nombre de paires si pairing=random
  random_k: 10

  # Paramètres de génération
  max_new_tokens: 200
  temperature: 0.7

  # Dossier de sortie (création: RUN_YYYYMMDD_HHMM_n°XXX)
  runs_dir: "./runs"

  # Banque de prompts (doit contenir des {id,text})
  prompts_file: "./configs/prompts.yaml"

  # Filtres modèles (motifs ou IDs exacts)
  include: []   # ex: ["meta-llama", "HuggingFaceH4/zephyr-7b-beta"]
  exclude: []   # ex: ["deepseek-ai/DeepSeek-V3"]

  # Restreindre aux prompts par ID (vide = tous)
  prompt_ids: []   # ex: [1,3,5]

  # Verbosité, seed, debug
  quiet: false
  seed: 0
  debug: false
